### ISSUE TITLE
Unable to split YouTube videos using 4-stems

### ISSUE THREAD

**Issue by adigrateles** [thepirat000/spleeter-api#1]
As of 4 December 2019, 04:00:00 (UTC), attempts to split music through new YouTube links leads to the following error:

![image](https://user-images.githubusercontent.com/9836384/70113194-3a292500-1693-11ea-86b8-c020305d907d.png)

Split was attempted using 4-stem and 2-stem models; all output options (zip, mp3, mp4) were tested.

Notably, YouTube links used prior to the above date are able to output split files without issue, but this seems to be dependent on the stem chosen. e.g. If a file was previously split using 2-stem model, it cannot be split using 4-stem or 5-stem models.

**Comment by thepirat000** [comment]
sometimes a python process keeps consuming memory until it make the other processes to fail and I have too manually kill the stale process.. I guess that was the problem. Please try again now

**Comment by adigrateles** [comment]
New YouTube links are working now.
