### ISSUE TITLE
ERROR: Server responded with 0 code.

### ISSUE THREAD

**Issue by CHJ85** [thepirat000/spleeter-api#10]
Hi. I tried this but with no luck. First I downloaded and tried it locally with no luck. Then I tried your online demo with no luck still.
```
Some files cannot be processed:
Server responded with 0 code.
```

**Comment by thepirat000** [comment]
It's fixed now, it was because of low disk space on the VM and an outdated version of youtube-dl.

Please try again

**Comment by CHJ85** [comment]
Okay great. Thanks.
