### ISSUE TITLE
Can I use the repo to rip/extract audio from MP4 format video?

### ISSUE THREAD

**Issue by zydjohnHotmail** [thepirat000/spleeter-api#11]
Hello:
I found the repo., it seems to be interesting.  Now I have 2 questions about the repo.
1) Can I use the repo to rip or extract audio from a MP4 format video.  FFMPEG can do this.  Let me know if the repo can do this or not.
2) If I have one big audio (MP3 format) file, for example, if I extract the audio from one MP4 file (Like: C:\Videos\1.mp4), and save it as 1.mp3, let’s say this MP3 file has length of 10 minutes, can I split the MP3 file into many parts at exact time position, for example: from time 1 minute 10 seconds to 3 minute 1 second and from 7.5 minute to 9 minute.
Let me know if the repo can do the above jobs.
Thanks,

**Comment by thepirat000** [comment]
No, that's not the purpose of this repo.

You can extract audio and split it with multiple tools, for example ffmpeg.

This tool is to separate the different instruments in an audio file
