### ISSUE TITLE
Spleeter GPU or CPU

### ISSUE THREAD

**Issue by ergodaveh** [thepirat000/spleeter-api#13]
Is there a method to determine/check which Spleeter processing is currently being using?

**Comment by thepirat000** [comment]
No, but it's CPU since I cannot afford a VM with GPU 24/7

**Comment by ergodaveh** [comment]
Know that pain.:) .

nice work,  started a local clone late last week
an older processor Intel(R) Core(TM) i7 CPU 960  @ 3.20GHz   3.20 GHz
with a NVIDIA GeForce GT 730
and honestly cannot recall which options was chosen.
