### ISSUE TITLE
Spleeter-api on Windows Machine

### ISSUE THREAD

**Issue by abokhalel2** [thepirat000/spleeter-api#2]
Hi,

Thank you for the amazing project.

I'm using Standard D2 Azure VM, and I was not able to make the project run on localhost or public IP.

The installation was a success without errors or warning:

![Screen-Shot](https://i.postimg.cc/1RKKjfw9/Screen-Shot-2020-03-15-at-2-58-55-PM.png)

Then, I run this command inside "C:\git\spleeter-api\bin\Release\netcoreapp3.0\publish\" :

`dotnet C:\git\spleeter-api\bin\Release\netcoreapp3.0\publish\SpleeterAPI.dll --https_enabled false
`

The results seems working, but I'm not sure if it is the right command:

![Screen-Shot](https://i.postimg.cc/m2YhwHHw/Screen-Shot-2020-03-15-at-4-54-50-PM.png)

I tried opening  http://localhost:5000 or https://localhost:5001, and nothing works.

What am I missing here, How can the project run locally?

**Comment by thepirat000** [comment]
Try with http://localhost:5000/test or https://localhost:5001/test on a browser.

Then there is the index.html static page [here](https://github.com/thepirat000/spleeter-api/blob/master/docs/index.html). You can open this file locally or publish the /docs folder contents to a web server.

And you should change this var on the js to point to your URL: https://github.com/thepirat000/spleeter-api/blob/master/docs/splitter.js#L8

**Comment by abokhalel2** [comment]
Thank you! I appreciate your help.
