### ISSUE TITLE
This localhost page can’t be found

### ISSUE THREAD

**Issue by ytautomate** [thepirat000/spleeter-api#3]
I installed the api locally on my window machine. When I started the application using command: dotnet C:\git\spleeter-api\bin\Release\netcoreapp3.0\publish\SpleeterAPI.dll --https_enabled false
it started correctly:
Spleeter started at 5/15/2020 10:06:23 AM. ENV: Production
Information: Now listening on: http://localhost:5000
Information: Now listening on: https://localhost:5001

However, when I go the the local host urls, I found this error message:
This localhost page can’t be foundNo webpage was found for the web address: https://localhost:5001/
HTTP ERROR 404
I am not sure how to use the api after it is installed locally. Any advice?

**Comment by thepirat000** [comment]
Try https://localhost:5001/swagger or https://localhost:5001/test

**Comment by ytautomate** [comment]
Thanks a lot! It went through the swagger UI. Is this how it is supposed to use locally, not something interactive like the demo URL you showed in Readme.md?

**Comment by thepirat000** [comment]
yes that's the API. the UI part is on the docs folder. docs/index.html. it's just a static HTML with some JavaScript

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ytautomate** [comment]
Thanks for your prompt response! Can you also advice how I can connect the UI in docs/index.html to the localhost API so I can create stems locally? The demo web app in the readme.md keeps on throwing errors when I try to use it. It seems to be a server error. Thanks for your help!
