### ISSUE TITLE
Requests are not queued up

### ISSUE THREAD

**Issue by ytautomate** [thepirat000/spleeter-api#5]
The requests are not processed in queue. If the program is processing a song when it receives a new request, the on-going process will be abandoned in favor to the new one. How do I get it to queue up requests and process them in the order they are received?

**Comment by thepirat000** [comment]
Actually the requests can be processed in parallel. I've requested up to 3 splits at once and worked just fine. The problem will be the GPU running out of memory very quickly. 

There is no queue implementation since this was designed for personal use only.

**Comment by ytautomate** [comment]
Cool. Thanks for the information! I wish that you could add the queue implementation in future update
