### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by wileyfoxyx** [thepirat000/spleeter-api#6]
![image](https://user-images.githubusercontent.com/46865008/87035719-66d98800-c1f2-11ea-9401-983080bd5af2.png)

**Comment by thepirat000** [comment]
When that happens, it means the processing server is down, mostly because my MSDN subscription has reached the spent limit. And that's the case right now. I won't be able to turn on the server until July 19, when my subscription renews.

**Comment by thepirat000** [comment]
working now
