### ISSUE TITLE
Exited with code -1

### ISSUE THREAD

**Issue by ceebu** [thepirat000/spleeter-api#9]
Tried to use it for separate the following youtube video - https://www.youtube.com/watch?v=B_pvwVLv4os
 Got error "Exited with code -1"

![spleeter-error](https://user-images.githubusercontent.com/12643238/108166263-f399dc00-7119-11eb-955d-59c352170a1e.jpg)

**Comment by thepirat000** [comment]
It did worked for me, please try again
